### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by Lyssers** [Nostalgia-09/wlm-09-discord#2]
Using either the release or cloning it just results in a white screen after sign-in.
![image](https://github.com/Nostalgia-09/wlm-09-discord/assets/37519050/52e0b7e5-30c9-44ed-8009-00d06800e04c)

**Comment by not-nullptr** [comment]
could you send screenshots of any errors in devtools? ctrl + shift + i, go into the console tab and scroll up until you see some red errors. preferably do this on a cloned dev build instead of the releases.

**Comment by Lyssers** [comment]
Of course, no problem:
![image](https://github.com/Nostalgia-09/wlm-09-discord/assets/37519050/de1657df-ab0c-4275-bbda-57409622361d)

Love the app btw, let me know if there's anything else I can do to help

**Comment by not-nullptr** [comment]
this is very helpful. try pulling from upstream and running a dev build now

**Comment by not-nullptr** [comment]
this issue is stale, try the latest release
