### ISSUE TITLE
Javascript error when launching wlm-09-discord

### ISSUE THREAD

**Issue by StupidGameridk** [Nostalgia-09/wlm-09-discord#3]
![javascript error](https://github.com/Nostalgia-09/wlm-09-discord/assets/125389741/4193f82e-1b95-415b-9977-fbc3454aeddc)

I updated from version 3 to 4 and I get this, I have tried uninstalling and reinstalling but it still shows the same error

**Comment by not-nullptr** [comment]
regression caused by a bug with the way i built the project. give me a few minutes.
