### ISSUE TITLE
Older Windows Support

### ISSUE THREAD

**Issue by freedom7341** [Nostalgia-09/wlm-09-discord#5]
Since this program is dedicated to providing a classic look and feel as an Instant Messaging client would, why would it not run on older versions of Windows? I feel 7 and 8.1 support isn't too much to ask for considering the era of this program.
![image](https://github.com/Nostalgia-09/wlm-09-discord/assets/36094486/7a25a35a-69df-4e31-8ba3-073782f92576)

**Comment by not-nullptr** [comment]
this is an issue to raise with any extended kernel developers or the electron developers.

**Comment by freedom7341** [comment]
I believe that this is an issue to raise here as it could be rebased on a version of electron that supports 7/8, as Discord still does. Can you please not brush off the issue?

**Comment by not-nullptr** [comment]
i am not brushing off the issue, nor am i going to downgrade to an older version of electron. your decision to use an outdated os is *not* my problem, and i should be able to utilize the latest apis, whether or not you want backwards compatibility. this software is intended for use with nostalgia 09, which is based off 22h2.
